spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/etc
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
  root: info